// Code generated by go-swagger; DO NOT EDIT.

// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
// 	http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// BlockTopology Block device topology exposed to the guest via VIRTIO_BLK_F_TOPOLOGY. When value is present, it is used instead of Firecracker defaults. All I/O size fields are expressed in units of logical blocks. This field is optional for virtio-block config and should be omitted for vhost-user-block configuration.
//
// swagger:model BlockTopology
type BlockTopology struct {

	// Offset of the first aligned logical block.
	AlignmentOffset int64 `json:"alignment_offset,omitempty"`

	// Suggested minimum I/O size, in units of logical blocks.
	MinIoSize int64 `json:"min_io_size,omitempty"`

	// Suggested optimal (maximum) I/O size, in units of logical blocks.
	OptIoSize int64 `json:"opt_io_size,omitempty"`

	// log2 of the number of logical blocks per physical block.
	PhysicalBlockExp int64 `json:"physical_block_exp,omitempty"`
}

// Validate validates this block topology
func (m *BlockTopology) Validate(_ strfmt.Registry) error {
	return nil
}

// ContextValidate validates this block topology based on context it is used
func (m *BlockTopology) ContextValidate(_ context.Context, _ strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BlockTopology) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BlockTopology) UnmarshalBinary(b []byte) error {
	var res BlockTopology
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
