// Code generated by go-swagger; DO NOT EDIT.

// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
// 	http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// MemoryHotplugSizeUpdate An update to the size of the hotpluggable memory region.
//
// swagger:model MemoryHotplugSizeUpdate
type MemoryHotplugSizeUpdate struct {

	// New target region size.
	// Maximum: 4.294967295e+09
	// Minimum: 0
	RequestedSizeMib *int64 `json:"requested_size_mib,omitempty"`
}

// Validate validates this memory hotplug size update
func (m *MemoryHotplugSizeUpdate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRequestedSizeMib(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MemoryHotplugSizeUpdate) validateRequestedSizeMib(formats strfmt.Registry) error {
	if typeutils.IsZero(m.RequestedSizeMib) { // not required
		return nil
	}

	if err := validate.MinimumInt("requested_size_mib", "body", *m.RequestedSizeMib, 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("requested_size_mib", "body", *m.RequestedSizeMib, 4.294967295e+09, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this memory hotplug size update based on context it is used
func (m *MemoryHotplugSizeUpdate) ContextValidate(_ context.Context, _ strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MemoryHotplugSizeUpdate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MemoryHotplugSizeUpdate) UnmarshalBinary(b []byte) error {
	var res MemoryHotplugSizeUpdate
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
