// Code generated by go-swagger; DO NOT EDIT.

// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
// 	http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// MemoryHotplugConfig The configuration of the hotpluggable memory device (virtio-mem)
//
// swagger:model MemoryHotplugConfig
type MemoryHotplugConfig struct {

	// (Logical) Block size for the hotpluggable memory in MiB. This will determine the logical granularity of hot-plug memory for the guest. Refer to the device documentation on how to tune this value.
	// Maximum: 4.294967295e+09
	// Minimum: 2
	BlockSizeMib int64 `json:"block_size_mib,omitempty"`

	// Slot size for the hotpluggable memory in MiB. This will determine the granularity of hot-plug memory from the host. Refer to the device documentation on how to tune this value.
	// Maximum: 4.294967295e+09
	// Minimum: 128
	SlotSizeMib int64 `json:"slot_size_mib,omitempty"`

	// Total size of the hotpluggable memory in MiB.
	// Maximum: 4.294967295e+09
	TotalSizeMib int64 `json:"total_size_mib,omitempty"`
}

// Validate validates this memory hotplug config
func (m *MemoryHotplugConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBlockSizeMib(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSlotSizeMib(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTotalSizeMib(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MemoryHotplugConfig) validateBlockSizeMib(formats strfmt.Registry) error {
	if typeutils.IsZero(m.BlockSizeMib) { // not required
		return nil
	}

	if err := validate.MinimumInt("block_size_mib", "body", m.BlockSizeMib, 2, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("block_size_mib", "body", m.BlockSizeMib, 4.294967295e+09, false); err != nil {
		return err
	}

	return nil
}

func (m *MemoryHotplugConfig) validateSlotSizeMib(formats strfmt.Registry) error {
	if typeutils.IsZero(m.SlotSizeMib) { // not required
		return nil
	}

	if err := validate.MinimumInt("slot_size_mib", "body", m.SlotSizeMib, 128, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("slot_size_mib", "body", m.SlotSizeMib, 4.294967295e+09, false); err != nil {
		return err
	}

	return nil
}

func (m *MemoryHotplugConfig) validateTotalSizeMib(formats strfmt.Registry) error {
	if typeutils.IsZero(m.TotalSizeMib) { // not required
		return nil
	}

	if err := validate.MaximumInt("total_size_mib", "body", m.TotalSizeMib, 4.294967295e+09, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this memory hotplug config based on context it is used
func (m *MemoryHotplugConfig) ContextValidate(_ context.Context, _ strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MemoryHotplugConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MemoryHotplugConfig) UnmarshalBinary(b []byte) error {
	var res MemoryHotplugConfig
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
