// Code generated by go-swagger; DO NOT EDIT.

// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
// 	http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

package operations

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDescribeBalloonStatsParams creates a new DescribeBalloonStatsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDescribeBalloonStatsParams() *DescribeBalloonStatsParams {
	return NewDescribeBalloonStatsParamsWithTimeout(cr.DefaultTimeout)
}

// NewDescribeBalloonStatsParamsWithTimeout creates a new DescribeBalloonStatsParams object
// with the ability to set a timeout on a request.
func NewDescribeBalloonStatsParamsWithTimeout(timeout time.Duration) *DescribeBalloonStatsParams {
	return &DescribeBalloonStatsParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewDescribeBalloonStatsParamsWithContext creates a new DescribeBalloonStatsParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [DescribeBalloonStatsParams].
func NewDescribeBalloonStatsParamsWithContext(ctx context.Context) *DescribeBalloonStatsParams {
	return &DescribeBalloonStatsParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewDescribeBalloonStatsParamsWithHTTPClient creates a new DescribeBalloonStatsParams object
// with the ability to set a custom HTTPClient for a request.
func NewDescribeBalloonStatsParamsWithHTTPClient(client *http.Client) *DescribeBalloonStatsParams {
	return &DescribeBalloonStatsParams{
		HTTPClient: client,
	}
}

/*
DescribeBalloonStatsParams contains all the parameters to send to the API endpoint

	for the describe balloon stats operation.

	Typically these are written to a http.Request.
*/
type DescribeBalloonStatsParams struct {
	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the describe balloon stats params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DescribeBalloonStatsParams) WithDefaults() *DescribeBalloonStatsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the describe balloon stats params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DescribeBalloonStatsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the describe balloon stats params.
func (o *DescribeBalloonStatsParams) WithTimeout(timeout time.Duration) *DescribeBalloonStatsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the describe balloon stats params.
func (o *DescribeBalloonStatsParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the describe balloon stats params.
//
// Deprecated: use the operation call with context to pass the context instead of [DescribeBalloonStatsParams].
func (o *DescribeBalloonStatsParams) WithContext(ctx context.Context) *DescribeBalloonStatsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the describe balloon stats params.
//
// Deprecated: use the operation call with context to pass the context instead of [DescribeBalloonStatsParams].
func (o *DescribeBalloonStatsParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the describe balloon stats params.
func (o *DescribeBalloonStatsParams) WithHTTPClient(client *http.Client) *DescribeBalloonStatsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the describe balloon stats params.
func (o *DescribeBalloonStatsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *DescribeBalloonStatsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
