// Code generated by go-swagger; DO NOT EDIT.

// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
// 	http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

package operations

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetMemoryHotplugParams creates a new GetMemoryHotplugParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMemoryHotplugParams() *GetMemoryHotplugParams {
	return NewGetMemoryHotplugParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetMemoryHotplugParamsWithTimeout creates a new GetMemoryHotplugParams object
// with the ability to set a timeout on a request.
func NewGetMemoryHotplugParamsWithTimeout(timeout time.Duration) *GetMemoryHotplugParams {
	return &GetMemoryHotplugParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetMemoryHotplugParamsWithContext creates a new GetMemoryHotplugParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetMemoryHotplugParams].
func NewGetMemoryHotplugParamsWithContext(ctx context.Context) *GetMemoryHotplugParams {
	return &GetMemoryHotplugParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetMemoryHotplugParamsWithHTTPClient creates a new GetMemoryHotplugParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMemoryHotplugParamsWithHTTPClient(client *http.Client) *GetMemoryHotplugParams {
	return &GetMemoryHotplugParams{
		HTTPClient: client,
	}
}

/*
GetMemoryHotplugParams contains all the parameters to send to the API endpoint

	for the get memory hotplug operation.

	Typically these are written to a http.Request.
*/
type GetMemoryHotplugParams struct {
	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get memory hotplug params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMemoryHotplugParams) WithDefaults() *GetMemoryHotplugParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get memory hotplug params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMemoryHotplugParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get memory hotplug params.
func (o *GetMemoryHotplugParams) WithTimeout(timeout time.Duration) *GetMemoryHotplugParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get memory hotplug params.
func (o *GetMemoryHotplugParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get memory hotplug params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetMemoryHotplugParams].
func (o *GetMemoryHotplugParams) WithContext(ctx context.Context) *GetMemoryHotplugParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get memory hotplug params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetMemoryHotplugParams].
func (o *GetMemoryHotplugParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get memory hotplug params.
func (o *GetMemoryHotplugParams) WithHTTPClient(client *http.Client) *GetMemoryHotplugParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get memory hotplug params.
func (o *GetMemoryHotplugParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetMemoryHotplugParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
