// Code generated by go-swagger; DO NOT EDIT.

// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
// 	http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

package operations

import (
	"context"
	"net/http"
	"time"

	"github.com/firecracker-microvm/firecracker-go-sdk/client/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutSerialDeviceParams creates a new PutSerialDeviceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutSerialDeviceParams() *PutSerialDeviceParams {
	return NewPutSerialDeviceParamsWithTimeout(cr.DefaultTimeout)
}

// NewPutSerialDeviceParamsWithTimeout creates a new PutSerialDeviceParams object
// with the ability to set a timeout on a request.
func NewPutSerialDeviceParamsWithTimeout(timeout time.Duration) *PutSerialDeviceParams {
	return &PutSerialDeviceParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPutSerialDeviceParamsWithContext creates a new PutSerialDeviceParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PutSerialDeviceParams].
func NewPutSerialDeviceParamsWithContext(ctx context.Context) *PutSerialDeviceParams {
	return &PutSerialDeviceParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPutSerialDeviceParamsWithHTTPClient creates a new PutSerialDeviceParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutSerialDeviceParamsWithHTTPClient(client *http.Client) *PutSerialDeviceParams {
	return &PutSerialDeviceParams{
		HTTPClient: client,
	}
}

/*
PutSerialDeviceParams contains all the parameters to send to the API endpoint

	for the put serial device operation.

	Typically these are written to a http.Request.
*/
type PutSerialDeviceParams struct {

	// Body.
	//
	// Serial console properties
	Body *models.SerialDevice

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the put serial device params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutSerialDeviceParams) WithDefaults() *PutSerialDeviceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put serial device params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutSerialDeviceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put serial device params.
func (o *PutSerialDeviceParams) WithTimeout(timeout time.Duration) *PutSerialDeviceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put serial device params.
func (o *PutSerialDeviceParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the put serial device params.
//
// Deprecated: use the operation call with context to pass the context instead of [PutSerialDeviceParams].
func (o *PutSerialDeviceParams) WithContext(ctx context.Context) *PutSerialDeviceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put serial device params.
//
// Deprecated: use the operation call with context to pass the context instead of [PutSerialDeviceParams].
func (o *PutSerialDeviceParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the put serial device params.
func (o *PutSerialDeviceParams) WithHTTPClient(client *http.Client) *PutSerialDeviceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put serial device params.
func (o *PutSerialDeviceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put serial device params.
func (o *PutSerialDeviceParams) WithBody(body *models.SerialDevice) *PutSerialDeviceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put serial device params.
func (o *PutSerialDeviceParams) SetBody(body *models.SerialDevice) {
	o.Body = body
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PutSerialDeviceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
