// Code generated by go-swagger; DO NOT EDIT.

// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
// 	http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

package operations

import (
	"context"
	"net/http"
	"time"

	"github.com/firecracker-microvm/firecracker-go-sdk/client/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutCPUConfigurationParams creates a new PutCPUConfigurationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutCPUConfigurationParams() *PutCPUConfigurationParams {
	return NewPutCPUConfigurationParamsWithTimeout(cr.DefaultTimeout)
}

// NewPutCPUConfigurationParamsWithTimeout creates a new PutCPUConfigurationParams object
// with the ability to set a timeout on a request.
func NewPutCPUConfigurationParamsWithTimeout(timeout time.Duration) *PutCPUConfigurationParams {
	return &PutCPUConfigurationParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPutCPUConfigurationParamsWithContext creates a new PutCPUConfigurationParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PutCPUConfigurationParams].
func NewPutCPUConfigurationParamsWithContext(ctx context.Context) *PutCPUConfigurationParams {
	return &PutCPUConfigurationParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPutCPUConfigurationParamsWithHTTPClient creates a new PutCPUConfigurationParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutCPUConfigurationParamsWithHTTPClient(client *http.Client) *PutCPUConfigurationParams {
	return &PutCPUConfigurationParams{
		HTTPClient: client,
	}
}

/*
PutCPUConfigurationParams contains all the parameters to send to the API endpoint

	for the put Cpu configuration operation.

	Typically these are written to a http.Request.
*/
type PutCPUConfigurationParams struct {

	// Body.
	//
	// CPU configuration request
	Body *models.CPUConfig

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the put Cpu configuration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutCPUConfigurationParams) WithDefaults() *PutCPUConfigurationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put Cpu configuration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutCPUConfigurationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put Cpu configuration params.
func (o *PutCPUConfigurationParams) WithTimeout(timeout time.Duration) *PutCPUConfigurationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put Cpu configuration params.
func (o *PutCPUConfigurationParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the put Cpu configuration params.
//
// Deprecated: use the operation call with context to pass the context instead of [PutCPUConfigurationParams].
func (o *PutCPUConfigurationParams) WithContext(ctx context.Context) *PutCPUConfigurationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put Cpu configuration params.
//
// Deprecated: use the operation call with context to pass the context instead of [PutCPUConfigurationParams].
func (o *PutCPUConfigurationParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the put Cpu configuration params.
func (o *PutCPUConfigurationParams) WithHTTPClient(client *http.Client) *PutCPUConfigurationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put Cpu configuration params.
func (o *PutCPUConfigurationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put Cpu configuration params.
func (o *PutCPUConfigurationParams) WithBody(body *models.CPUConfig) *PutCPUConfigurationParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put Cpu configuration params.
func (o *PutCPUConfigurationParams) SetBody(body *models.CPUConfig) {
	o.Body = body
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PutCPUConfigurationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
