// Code generated by go-swagger; DO NOT EDIT.

// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
// 	http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

package operations

import (
	"context"
	"net/http"
	"time"

	"github.com/firecracker-microvm/firecracker-go-sdk/client/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewStartBalloonHintingParams creates a new StartBalloonHintingParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStartBalloonHintingParams() *StartBalloonHintingParams {
	return NewStartBalloonHintingParamsWithTimeout(cr.DefaultTimeout)
}

// NewStartBalloonHintingParamsWithTimeout creates a new StartBalloonHintingParams object
// with the ability to set a timeout on a request.
func NewStartBalloonHintingParamsWithTimeout(timeout time.Duration) *StartBalloonHintingParams {
	return &StartBalloonHintingParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewStartBalloonHintingParamsWithContext creates a new StartBalloonHintingParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [StartBalloonHintingParams].
func NewStartBalloonHintingParamsWithContext(ctx context.Context) *StartBalloonHintingParams {
	return &StartBalloonHintingParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewStartBalloonHintingParamsWithHTTPClient creates a new StartBalloonHintingParams object
// with the ability to set a custom HTTPClient for a request.
func NewStartBalloonHintingParamsWithHTTPClient(client *http.Client) *StartBalloonHintingParams {
	return &StartBalloonHintingParams{
		HTTPClient: client,
	}
}

/*
StartBalloonHintingParams contains all the parameters to send to the API endpoint

	for the start balloon hinting operation.

	Typically these are written to a http.Request.
*/
type StartBalloonHintingParams struct {

	// Body.
	//
	// When the device completes the hinting whether we should automatically ack this.
	Body *models.BalloonStartCmd

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the start balloon hinting params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StartBalloonHintingParams) WithDefaults() *StartBalloonHintingParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the start balloon hinting params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StartBalloonHintingParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the start balloon hinting params.
func (o *StartBalloonHintingParams) WithTimeout(timeout time.Duration) *StartBalloonHintingParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the start balloon hinting params.
func (o *StartBalloonHintingParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the start balloon hinting params.
//
// Deprecated: use the operation call with context to pass the context instead of [StartBalloonHintingParams].
func (o *StartBalloonHintingParams) WithContext(ctx context.Context) *StartBalloonHintingParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the start balloon hinting params.
//
// Deprecated: use the operation call with context to pass the context instead of [StartBalloonHintingParams].
func (o *StartBalloonHintingParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the start balloon hinting params.
func (o *StartBalloonHintingParams) WithHTTPClient(client *http.Client) *StartBalloonHintingParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the start balloon hinting params.
func (o *StartBalloonHintingParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the start balloon hinting params.
func (o *StartBalloonHintingParams) WithBody(body *models.BalloonStartCmd) *StartBalloonHintingParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the start balloon hinting params.
func (o *StartBalloonHintingParams) SetBody(body *models.BalloonStartCmd) {
	o.Body = body
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *StartBalloonHintingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
