// Code generated by go-swagger; DO NOT EDIT.

// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
// 	http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

package operations

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDescribeBalloonHintingParams creates a new DescribeBalloonHintingParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDescribeBalloonHintingParams() *DescribeBalloonHintingParams {
	return NewDescribeBalloonHintingParamsWithTimeout(cr.DefaultTimeout)
}

// NewDescribeBalloonHintingParamsWithTimeout creates a new DescribeBalloonHintingParams object
// with the ability to set a timeout on a request.
func NewDescribeBalloonHintingParamsWithTimeout(timeout time.Duration) *DescribeBalloonHintingParams {
	return &DescribeBalloonHintingParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewDescribeBalloonHintingParamsWithContext creates a new DescribeBalloonHintingParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [DescribeBalloonHintingParams].
func NewDescribeBalloonHintingParamsWithContext(ctx context.Context) *DescribeBalloonHintingParams {
	return &DescribeBalloonHintingParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewDescribeBalloonHintingParamsWithHTTPClient creates a new DescribeBalloonHintingParams object
// with the ability to set a custom HTTPClient for a request.
func NewDescribeBalloonHintingParamsWithHTTPClient(client *http.Client) *DescribeBalloonHintingParams {
	return &DescribeBalloonHintingParams{
		HTTPClient: client,
	}
}

/*
DescribeBalloonHintingParams contains all the parameters to send to the API endpoint

	for the describe balloon hinting operation.

	Typically these are written to a http.Request.
*/
type DescribeBalloonHintingParams struct {
	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the describe balloon hinting params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DescribeBalloonHintingParams) WithDefaults() *DescribeBalloonHintingParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the describe balloon hinting params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DescribeBalloonHintingParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the describe balloon hinting params.
func (o *DescribeBalloonHintingParams) WithTimeout(timeout time.Duration) *DescribeBalloonHintingParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the describe balloon hinting params.
func (o *DescribeBalloonHintingParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the describe balloon hinting params.
//
// Deprecated: use the operation call with context to pass the context instead of [DescribeBalloonHintingParams].
func (o *DescribeBalloonHintingParams) WithContext(ctx context.Context) *DescribeBalloonHintingParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the describe balloon hinting params.
//
// Deprecated: use the operation call with context to pass the context instead of [DescribeBalloonHintingParams].
func (o *DescribeBalloonHintingParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the describe balloon hinting params.
func (o *DescribeBalloonHintingParams) WithHTTPClient(client *http.Client) *DescribeBalloonHintingParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the describe balloon hinting params.
func (o *DescribeBalloonHintingParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *DescribeBalloonHintingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
