// Code generated by go-swagger; DO NOT EDIT.

// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
// 	http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

package operations

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewStopBalloonHintingParams creates a new StopBalloonHintingParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStopBalloonHintingParams() *StopBalloonHintingParams {
	return NewStopBalloonHintingParamsWithTimeout(cr.DefaultTimeout)
}

// NewStopBalloonHintingParamsWithTimeout creates a new StopBalloonHintingParams object
// with the ability to set a timeout on a request.
func NewStopBalloonHintingParamsWithTimeout(timeout time.Duration) *StopBalloonHintingParams {
	return &StopBalloonHintingParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewStopBalloonHintingParamsWithContext creates a new StopBalloonHintingParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [StopBalloonHintingParams].
func NewStopBalloonHintingParamsWithContext(ctx context.Context) *StopBalloonHintingParams {
	return &StopBalloonHintingParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewStopBalloonHintingParamsWithHTTPClient creates a new StopBalloonHintingParams object
// with the ability to set a custom HTTPClient for a request.
func NewStopBalloonHintingParamsWithHTTPClient(client *http.Client) *StopBalloonHintingParams {
	return &StopBalloonHintingParams{
		HTTPClient: client,
	}
}

/*
StopBalloonHintingParams contains all the parameters to send to the API endpoint

	for the stop balloon hinting operation.

	Typically these are written to a http.Request.
*/
type StopBalloonHintingParams struct {
	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the stop balloon hinting params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StopBalloonHintingParams) WithDefaults() *StopBalloonHintingParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the stop balloon hinting params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StopBalloonHintingParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the stop balloon hinting params.
func (o *StopBalloonHintingParams) WithTimeout(timeout time.Duration) *StopBalloonHintingParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stop balloon hinting params.
func (o *StopBalloonHintingParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the stop balloon hinting params.
//
// Deprecated: use the operation call with context to pass the context instead of [StopBalloonHintingParams].
func (o *StopBalloonHintingParams) WithContext(ctx context.Context) *StopBalloonHintingParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stop balloon hinting params.
//
// Deprecated: use the operation call with context to pass the context instead of [StopBalloonHintingParams].
func (o *StopBalloonHintingParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the stop balloon hinting params.
func (o *StopBalloonHintingParams) WithHTTPClient(client *http.Client) *StopBalloonHintingParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the stop balloon hinting params.
func (o *StopBalloonHintingParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *StopBalloonHintingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
