// Code generated by go-swagger; DO NOT EDIT.

// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
// 	http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

package fctesting

import (
	"context"

	ops "github.com/firecracker-microvm/firecracker-go-sdk/client/operations"
	"github.com/go-openapi/runtime"
)

type MockClient struct {
	CreateSnapshotFn                        func(params *ops.CreateSnapshotParams, opts ...ops.ClientOption) (*ops.CreateSnapshotNoContent, error)
	CreateSnapshotContextFn                 func(ctx context.Context, params *ops.CreateSnapshotParams, opts ...ops.ClientOption) (*ops.CreateSnapshotNoContent, error)
	CreateSyncActionFn                      func(params *ops.CreateSyncActionParams, opts ...ops.ClientOption) (*ops.CreateSyncActionNoContent, error)
	CreateSyncActionContextFn               func(ctx context.Context, params *ops.CreateSyncActionParams, opts ...ops.ClientOption) (*ops.CreateSyncActionNoContent, error)
	DescribeBalloonConfigFn                 func(params *ops.DescribeBalloonConfigParams, opts ...ops.ClientOption) (*ops.DescribeBalloonConfigOK, error)
	DescribeBalloonConfigContextFn          func(ctx context.Context, params *ops.DescribeBalloonConfigParams, opts ...ops.ClientOption) (*ops.DescribeBalloonConfigOK, error)
	DescribeBalloonHintingFn                func(params *ops.DescribeBalloonHintingParams, opts ...ops.ClientOption) (*ops.DescribeBalloonHintingOK, error)
	DescribeBalloonHintingContextFn         func(ctx context.Context, params *ops.DescribeBalloonHintingParams, opts ...ops.ClientOption) (*ops.DescribeBalloonHintingOK, error)
	DescribeBalloonStatsFn                  func(params *ops.DescribeBalloonStatsParams, opts ...ops.ClientOption) (*ops.DescribeBalloonStatsOK, error)
	DescribeBalloonStatsContextFn           func(ctx context.Context, params *ops.DescribeBalloonStatsParams, opts ...ops.ClientOption) (*ops.DescribeBalloonStatsOK, error)
	DescribeInstanceFn                      func(params *ops.DescribeInstanceParams, opts ...ops.ClientOption) (*ops.DescribeInstanceOK, error)
	DescribeInstanceContextFn               func(ctx context.Context, params *ops.DescribeInstanceParams, opts ...ops.ClientOption) (*ops.DescribeInstanceOK, error)
	GetExportVMConfigFn                     func(params *ops.GetExportVMConfigParams, opts ...ops.ClientOption) (*ops.GetExportVMConfigOK, error)
	GetExportVMConfigContextFn              func(ctx context.Context, params *ops.GetExportVMConfigParams, opts ...ops.ClientOption) (*ops.GetExportVMConfigOK, error)
	GetFirecrackerVersionFn                 func(params *ops.GetFirecrackerVersionParams, opts ...ops.ClientOption) (*ops.GetFirecrackerVersionOK, error)
	GetFirecrackerVersionContextFn          func(ctx context.Context, params *ops.GetFirecrackerVersionParams, opts ...ops.ClientOption) (*ops.GetFirecrackerVersionOK, error)
	GetMachineConfigurationFn               func(params *ops.GetMachineConfigurationParams, opts ...ops.ClientOption) (*ops.GetMachineConfigurationOK, error)
	GetMachineConfigurationContextFn        func(ctx context.Context, params *ops.GetMachineConfigurationParams, opts ...ops.ClientOption) (*ops.GetMachineConfigurationOK, error)
	GetMemoryHotplugFn                      func(params *ops.GetMemoryHotplugParams, opts ...ops.ClientOption) (*ops.GetMemoryHotplugOK, error)
	GetMemoryHotplugContextFn               func(ctx context.Context, params *ops.GetMemoryHotplugParams, opts ...ops.ClientOption) (*ops.GetMemoryHotplugOK, error)
	GetMmdsFn                               func(params *ops.GetMmdsParams, opts ...ops.ClientOption) (*ops.GetMmdsOK, error)
	GetMmdsContextFn                        func(ctx context.Context, params *ops.GetMmdsParams, opts ...ops.ClientOption) (*ops.GetMmdsOK, error)
	LoadSnapshotFn                          func(params *ops.LoadSnapshotParams, opts ...ops.ClientOption) (*ops.LoadSnapshotNoContent, error)
	LoadSnapshotContextFn                   func(ctx context.Context, params *ops.LoadSnapshotParams, opts ...ops.ClientOption) (*ops.LoadSnapshotNoContent, error)
	PatchBalloonFn                          func(params *ops.PatchBalloonParams, opts ...ops.ClientOption) (*ops.PatchBalloonNoContent, error)
	PatchBalloonContextFn                   func(ctx context.Context, params *ops.PatchBalloonParams, opts ...ops.ClientOption) (*ops.PatchBalloonNoContent, error)
	PatchBalloonStatsIntervalFn             func(params *ops.PatchBalloonStatsIntervalParams, opts ...ops.ClientOption) (*ops.PatchBalloonStatsIntervalNoContent, error)
	PatchBalloonStatsIntervalContextFn      func(ctx context.Context, params *ops.PatchBalloonStatsIntervalParams, opts ...ops.ClientOption) (*ops.PatchBalloonStatsIntervalNoContent, error)
	PatchGuestDriveByIDFn                   func(params *ops.PatchGuestDriveByIDParams, opts ...ops.ClientOption) (*ops.PatchGuestDriveByIDNoContent, error)
	PatchGuestDriveByIDContextFn            func(ctx context.Context, params *ops.PatchGuestDriveByIDParams, opts ...ops.ClientOption) (*ops.PatchGuestDriveByIDNoContent, error)
	PatchGuestNetworkInterfaceByIDFn        func(params *ops.PatchGuestNetworkInterfaceByIDParams, opts ...ops.ClientOption) (*ops.PatchGuestNetworkInterfaceByIDNoContent, error)
	PatchGuestNetworkInterfaceByIDContextFn func(ctx context.Context, params *ops.PatchGuestNetworkInterfaceByIDParams, opts ...ops.ClientOption) (*ops.PatchGuestNetworkInterfaceByIDNoContent, error)
	PatchGuestPmemByIDFn                    func(params *ops.PatchGuestPmemByIDParams, opts ...ops.ClientOption) (*ops.PatchGuestPmemByIDNoContent, error)
	PatchGuestPmemByIDContextFn             func(ctx context.Context, params *ops.PatchGuestPmemByIDParams, opts ...ops.ClientOption) (*ops.PatchGuestPmemByIDNoContent, error)
	PatchMachineConfigurationFn             func(params *ops.PatchMachineConfigurationParams, opts ...ops.ClientOption) (*ops.PatchMachineConfigurationNoContent, error)
	PatchMachineConfigurationContextFn      func(ctx context.Context, params *ops.PatchMachineConfigurationParams, opts ...ops.ClientOption) (*ops.PatchMachineConfigurationNoContent, error)
	PatchMemoryHotplugFn                    func(params *ops.PatchMemoryHotplugParams, opts ...ops.ClientOption) (*ops.PatchMemoryHotplugNoContent, error)
	PatchMemoryHotplugContextFn             func(ctx context.Context, params *ops.PatchMemoryHotplugParams, opts ...ops.ClientOption) (*ops.PatchMemoryHotplugNoContent, error)
	PatchMmdsFn                             func(params *ops.PatchMmdsParams, opts ...ops.ClientOption) (*ops.PatchMmdsNoContent, error)
	PatchMmdsContextFn                      func(ctx context.Context, params *ops.PatchMmdsParams, opts ...ops.ClientOption) (*ops.PatchMmdsNoContent, error)
	PatchVMFn                               func(params *ops.PatchVMParams, opts ...ops.ClientOption) (*ops.PatchVMNoContent, error)
	PatchVMContextFn                        func(ctx context.Context, params *ops.PatchVMParams, opts ...ops.ClientOption) (*ops.PatchVMNoContent, error)
	PutBalloonFn                            func(params *ops.PutBalloonParams, opts ...ops.ClientOption) (*ops.PutBalloonNoContent, error)
	PutBalloonContextFn                     func(ctx context.Context, params *ops.PutBalloonParams, opts ...ops.ClientOption) (*ops.PutBalloonNoContent, error)
	PutCPUConfigurationFn                   func(params *ops.PutCPUConfigurationParams, opts ...ops.ClientOption) (*ops.PutCPUConfigurationNoContent, error)
	PutCPUConfigurationContextFn            func(ctx context.Context, params *ops.PutCPUConfigurationParams, opts ...ops.ClientOption) (*ops.PutCPUConfigurationNoContent, error)
	PutEntropyDeviceFn                      func(params *ops.PutEntropyDeviceParams, opts ...ops.ClientOption) (*ops.PutEntropyDeviceNoContent, error)
	PutEntropyDeviceContextFn               func(ctx context.Context, params *ops.PutEntropyDeviceParams, opts ...ops.ClientOption) (*ops.PutEntropyDeviceNoContent, error)
	PutGuestBootSourceFn                    func(params *ops.PutGuestBootSourceParams, opts ...ops.ClientOption) (*ops.PutGuestBootSourceNoContent, error)
	PutGuestBootSourceContextFn             func(ctx context.Context, params *ops.PutGuestBootSourceParams, opts ...ops.ClientOption) (*ops.PutGuestBootSourceNoContent, error)
	PutGuestDriveByIDFn                     func(params *ops.PutGuestDriveByIDParams, opts ...ops.ClientOption) (*ops.PutGuestDriveByIDNoContent, error)
	PutGuestDriveByIDContextFn              func(ctx context.Context, params *ops.PutGuestDriveByIDParams, opts ...ops.ClientOption) (*ops.PutGuestDriveByIDNoContent, error)
	PutGuestNetworkInterfaceByIDFn          func(params *ops.PutGuestNetworkInterfaceByIDParams, opts ...ops.ClientOption) (*ops.PutGuestNetworkInterfaceByIDNoContent, error)
	PutGuestNetworkInterfaceByIDContextFn   func(ctx context.Context, params *ops.PutGuestNetworkInterfaceByIDParams, opts ...ops.ClientOption) (*ops.PutGuestNetworkInterfaceByIDNoContent, error)
	PutGuestPmemByIDFn                      func(params *ops.PutGuestPmemByIDParams, opts ...ops.ClientOption) (*ops.PutGuestPmemByIDNoContent, error)
	PutGuestPmemByIDContextFn               func(ctx context.Context, params *ops.PutGuestPmemByIDParams, opts ...ops.ClientOption) (*ops.PutGuestPmemByIDNoContent, error)
	PutGuestVsockFn                         func(params *ops.PutGuestVsockParams, opts ...ops.ClientOption) (*ops.PutGuestVsockNoContent, error)
	PutGuestVsockContextFn                  func(ctx context.Context, params *ops.PutGuestVsockParams, opts ...ops.ClientOption) (*ops.PutGuestVsockNoContent, error)
	PutLoggerFn                             func(params *ops.PutLoggerParams, opts ...ops.ClientOption) (*ops.PutLoggerNoContent, error)
	PutLoggerContextFn                      func(ctx context.Context, params *ops.PutLoggerParams, opts ...ops.ClientOption) (*ops.PutLoggerNoContent, error)
	PutMachineConfigurationFn               func(params *ops.PutMachineConfigurationParams, opts ...ops.ClientOption) (*ops.PutMachineConfigurationNoContent, error)
	PutMachineConfigurationContextFn        func(ctx context.Context, params *ops.PutMachineConfigurationParams, opts ...ops.ClientOption) (*ops.PutMachineConfigurationNoContent, error)
	PutMemoryHotplugFn                      func(params *ops.PutMemoryHotplugParams, opts ...ops.ClientOption) (*ops.PutMemoryHotplugNoContent, error)
	PutMemoryHotplugContextFn               func(ctx context.Context, params *ops.PutMemoryHotplugParams, opts ...ops.ClientOption) (*ops.PutMemoryHotplugNoContent, error)
	PutMetricsFn                            func(params *ops.PutMetricsParams, opts ...ops.ClientOption) (*ops.PutMetricsNoContent, error)
	PutMetricsContextFn                     func(ctx context.Context, params *ops.PutMetricsParams, opts ...ops.ClientOption) (*ops.PutMetricsNoContent, error)
	PutMmdsFn                               func(params *ops.PutMmdsParams, opts ...ops.ClientOption) (*ops.PutMmdsNoContent, error)
	PutMmdsContextFn                        func(ctx context.Context, params *ops.PutMmdsParams, opts ...ops.ClientOption) (*ops.PutMmdsNoContent, error)
	PutMmdsConfigFn                         func(params *ops.PutMmdsConfigParams, opts ...ops.ClientOption) (*ops.PutMmdsConfigNoContent, error)
	PutMmdsConfigContextFn                  func(ctx context.Context, params *ops.PutMmdsConfigParams, opts ...ops.ClientOption) (*ops.PutMmdsConfigNoContent, error)
	PutSerialDeviceFn                       func(params *ops.PutSerialDeviceParams, opts ...ops.ClientOption) (*ops.PutSerialDeviceNoContent, error)
	PutSerialDeviceContextFn                func(ctx context.Context, params *ops.PutSerialDeviceParams, opts ...ops.ClientOption) (*ops.PutSerialDeviceNoContent, error)
	StartBalloonHintingFn                   func(params *ops.StartBalloonHintingParams, opts ...ops.ClientOption) (*ops.StartBalloonHintingNoContent, error)
	StartBalloonHintingContextFn            func(ctx context.Context, params *ops.StartBalloonHintingParams, opts ...ops.ClientOption) (*ops.StartBalloonHintingNoContent, error)
	StopBalloonHintingFn                    func(params *ops.StopBalloonHintingParams, opts ...ops.ClientOption) (*ops.StopBalloonHintingNoContent, error)
	StopBalloonHintingContextFn             func(ctx context.Context, params *ops.StopBalloonHintingParams, opts ...ops.ClientOption) (*ops.StopBalloonHintingNoContent, error)
}

func (c *MockClient) CreateSnapshot(params *ops.CreateSnapshotParams, opts ...ops.ClientOption) (*ops.CreateSnapshotNoContent, error) {
	if c.CreateSnapshotFn != nil {
		return c.CreateSnapshotFn(params)
	}

	return nil, nil
}

func (c *MockClient) CreateSnapshotContext(ctx context.Context, params *ops.CreateSnapshotParams, opts ...ops.ClientOption) (*ops.CreateSnapshotNoContent, error) {
	if c.CreateSnapshotFn != nil {
		return c.CreateSnapshotFn(params)
	}

	return nil, nil
}

func (c *MockClient) CreateSyncAction(params *ops.CreateSyncActionParams, opts ...ops.ClientOption) (*ops.CreateSyncActionNoContent, error) {
	if c.CreateSyncActionFn != nil {
		return c.CreateSyncActionFn(params)
	}

	return nil, nil
}

func (c *MockClient) CreateSyncActionContext(ctx context.Context, params *ops.CreateSyncActionParams, opts ...ops.ClientOption) (*ops.CreateSyncActionNoContent, error) {
	if c.CreateSyncActionFn != nil {
		return c.CreateSyncActionFn(params)
	}

	return nil, nil
}

func (c *MockClient) DescribeBalloonConfig(params *ops.DescribeBalloonConfigParams, opts ...ops.ClientOption) (*ops.DescribeBalloonConfigOK, error) {
	if c.DescribeBalloonConfigFn != nil {
		return c.DescribeBalloonConfigFn(params)
	}

	return nil, nil
}

func (c *MockClient) DescribeBalloonConfigContext(ctx context.Context, params *ops.DescribeBalloonConfigParams, opts ...ops.ClientOption) (*ops.DescribeBalloonConfigOK, error) {
	if c.DescribeBalloonConfigFn != nil {
		return c.DescribeBalloonConfigFn(params)
	}

	return nil, nil
}

func (c *MockClient) DescribeBalloonHinting(params *ops.DescribeBalloonHintingParams, opts ...ops.ClientOption) (*ops.DescribeBalloonHintingOK, error) {
	if c.DescribeBalloonHintingFn != nil {
		return c.DescribeBalloonHintingFn(params)
	}

	return nil, nil
}

func (c *MockClient) DescribeBalloonHintingContext(ctx context.Context, params *ops.DescribeBalloonHintingParams, opts ...ops.ClientOption) (*ops.DescribeBalloonHintingOK, error) {
	if c.DescribeBalloonHintingFn != nil {
		return c.DescribeBalloonHintingFn(params)
	}

	return nil, nil
}

func (c *MockClient) DescribeBalloonStats(params *ops.DescribeBalloonStatsParams, opts ...ops.ClientOption) (*ops.DescribeBalloonStatsOK, error) {
	if c.DescribeBalloonStatsFn != nil {
		return c.DescribeBalloonStatsFn(params)
	}

	return nil, nil
}

func (c *MockClient) DescribeBalloonStatsContext(ctx context.Context, params *ops.DescribeBalloonStatsParams, opts ...ops.ClientOption) (*ops.DescribeBalloonStatsOK, error) {
	if c.DescribeBalloonStatsFn != nil {
		return c.DescribeBalloonStatsFn(params)
	}

	return nil, nil
}

func (c *MockClient) DescribeInstance(params *ops.DescribeInstanceParams, opts ...ops.ClientOption) (*ops.DescribeInstanceOK, error) {
	if c.DescribeInstanceFn != nil {
		return c.DescribeInstanceFn(params)
	}

	return nil, nil
}

func (c *MockClient) DescribeInstanceContext(ctx context.Context, params *ops.DescribeInstanceParams, opts ...ops.ClientOption) (*ops.DescribeInstanceOK, error) {
	if c.DescribeInstanceFn != nil {
		return c.DescribeInstanceFn(params)
	}

	return nil, nil
}

func (c *MockClient) GetExportVMConfig(params *ops.GetExportVMConfigParams, opts ...ops.ClientOption) (*ops.GetExportVMConfigOK, error) {
	if c.GetExportVMConfigFn != nil {
		return c.GetExportVMConfigFn(params)
	}

	return nil, nil
}

func (c *MockClient) GetExportVMConfigContext(ctx context.Context, params *ops.GetExportVMConfigParams, opts ...ops.ClientOption) (*ops.GetExportVMConfigOK, error) {
	if c.GetExportVMConfigFn != nil {
		return c.GetExportVMConfigFn(params)
	}

	return nil, nil
}

func (c *MockClient) GetFirecrackerVersion(params *ops.GetFirecrackerVersionParams, opts ...ops.ClientOption) (*ops.GetFirecrackerVersionOK, error) {
	if c.GetFirecrackerVersionFn != nil {
		return c.GetFirecrackerVersionFn(params)
	}

	return nil, nil
}

func (c *MockClient) GetFirecrackerVersionContext(ctx context.Context, params *ops.GetFirecrackerVersionParams, opts ...ops.ClientOption) (*ops.GetFirecrackerVersionOK, error) {
	if c.GetFirecrackerVersionFn != nil {
		return c.GetFirecrackerVersionFn(params)
	}

	return nil, nil
}

func (c *MockClient) GetMachineConfiguration(params *ops.GetMachineConfigurationParams, opts ...ops.ClientOption) (*ops.GetMachineConfigurationOK, error) {
	if c.GetMachineConfigurationFn != nil {
		return c.GetMachineConfigurationFn(params)
	}

	return nil, nil
}

func (c *MockClient) GetMachineConfigurationContext(ctx context.Context, params *ops.GetMachineConfigurationParams, opts ...ops.ClientOption) (*ops.GetMachineConfigurationOK, error) {
	if c.GetMachineConfigurationFn != nil {
		return c.GetMachineConfigurationFn(params)
	}

	return nil, nil
}

func (c *MockClient) GetMemoryHotplug(params *ops.GetMemoryHotplugParams, opts ...ops.ClientOption) (*ops.GetMemoryHotplugOK, error) {
	if c.GetMemoryHotplugFn != nil {
		return c.GetMemoryHotplugFn(params)
	}

	return nil, nil
}

func (c *MockClient) GetMemoryHotplugContext(ctx context.Context, params *ops.GetMemoryHotplugParams, opts ...ops.ClientOption) (*ops.GetMemoryHotplugOK, error) {
	if c.GetMemoryHotplugFn != nil {
		return c.GetMemoryHotplugFn(params)
	}

	return nil, nil
}

func (c *MockClient) GetMmds(params *ops.GetMmdsParams, opts ...ops.ClientOption) (*ops.GetMmdsOK, error) {
	if c.GetMmdsFn != nil {
		return c.GetMmdsFn(params)
	}

	return nil, nil
}

func (c *MockClient) GetMmdsContext(ctx context.Context, params *ops.GetMmdsParams, opts ...ops.ClientOption) (*ops.GetMmdsOK, error) {
	if c.GetMmdsFn != nil {
		return c.GetMmdsFn(params)
	}

	return nil, nil
}

func (c *MockClient) LoadSnapshot(params *ops.LoadSnapshotParams, opts ...ops.ClientOption) (*ops.LoadSnapshotNoContent, error) {
	if c.LoadSnapshotFn != nil {
		return c.LoadSnapshotFn(params)
	}

	return nil, nil
}

func (c *MockClient) LoadSnapshotContext(ctx context.Context, params *ops.LoadSnapshotParams, opts ...ops.ClientOption) (*ops.LoadSnapshotNoContent, error) {
	if c.LoadSnapshotFn != nil {
		return c.LoadSnapshotFn(params)
	}

	return nil, nil
}

func (c *MockClient) PatchBalloon(params *ops.PatchBalloonParams, opts ...ops.ClientOption) (*ops.PatchBalloonNoContent, error) {
	if c.PatchBalloonFn != nil {
		return c.PatchBalloonFn(params)
	}

	return nil, nil
}

func (c *MockClient) PatchBalloonContext(ctx context.Context, params *ops.PatchBalloonParams, opts ...ops.ClientOption) (*ops.PatchBalloonNoContent, error) {
	if c.PatchBalloonFn != nil {
		return c.PatchBalloonFn(params)
	}

	return nil, nil
}

func (c *MockClient) PatchBalloonStatsInterval(params *ops.PatchBalloonStatsIntervalParams, opts ...ops.ClientOption) (*ops.PatchBalloonStatsIntervalNoContent, error) {
	if c.PatchBalloonStatsIntervalFn != nil {
		return c.PatchBalloonStatsIntervalFn(params)
	}

	return nil, nil
}

func (c *MockClient) PatchBalloonStatsIntervalContext(ctx context.Context, params *ops.PatchBalloonStatsIntervalParams, opts ...ops.ClientOption) (*ops.PatchBalloonStatsIntervalNoContent, error) {
	if c.PatchBalloonStatsIntervalFn != nil {
		return c.PatchBalloonStatsIntervalFn(params)
	}

	return nil, nil
}

func (c *MockClient) PatchGuestDriveByID(params *ops.PatchGuestDriveByIDParams, opts ...ops.ClientOption) (*ops.PatchGuestDriveByIDNoContent, error) {
	if c.PatchGuestDriveByIDFn != nil {
		return c.PatchGuestDriveByIDFn(params)
	}

	return nil, nil
}

func (c *MockClient) PatchGuestDriveByIDContext(ctx context.Context, params *ops.PatchGuestDriveByIDParams, opts ...ops.ClientOption) (*ops.PatchGuestDriveByIDNoContent, error) {
	if c.PatchGuestDriveByIDFn != nil {
		return c.PatchGuestDriveByIDFn(params)
	}

	return nil, nil
}

func (c *MockClient) PatchGuestNetworkInterfaceByID(params *ops.PatchGuestNetworkInterfaceByIDParams, opts ...ops.ClientOption) (*ops.PatchGuestNetworkInterfaceByIDNoContent, error) {
	if c.PatchGuestNetworkInterfaceByIDFn != nil {
		return c.PatchGuestNetworkInterfaceByIDFn(params)
	}

	return nil, nil
}

func (c *MockClient) PatchGuestNetworkInterfaceByIDContext(ctx context.Context, params *ops.PatchGuestNetworkInterfaceByIDParams, opts ...ops.ClientOption) (*ops.PatchGuestNetworkInterfaceByIDNoContent, error) {
	if c.PatchGuestNetworkInterfaceByIDFn != nil {
		return c.PatchGuestNetworkInterfaceByIDFn(params)
	}

	return nil, nil
}

func (c *MockClient) PatchGuestPmemByID(params *ops.PatchGuestPmemByIDParams, opts ...ops.ClientOption) (*ops.PatchGuestPmemByIDNoContent, error) {
	if c.PatchGuestPmemByIDFn != nil {
		return c.PatchGuestPmemByIDFn(params)
	}

	return nil, nil
}

func (c *MockClient) PatchGuestPmemByIDContext(ctx context.Context, params *ops.PatchGuestPmemByIDParams, opts ...ops.ClientOption) (*ops.PatchGuestPmemByIDNoContent, error) {
	if c.PatchGuestPmemByIDFn != nil {
		return c.PatchGuestPmemByIDFn(params)
	}

	return nil, nil
}

func (c *MockClient) PatchMachineConfiguration(params *ops.PatchMachineConfigurationParams, opts ...ops.ClientOption) (*ops.PatchMachineConfigurationNoContent, error) {
	if c.PatchMachineConfigurationFn != nil {
		return c.PatchMachineConfigurationFn(params)
	}

	return nil, nil
}

func (c *MockClient) PatchMachineConfigurationContext(ctx context.Context, params *ops.PatchMachineConfigurationParams, opts ...ops.ClientOption) (*ops.PatchMachineConfigurationNoContent, error) {
	if c.PatchMachineConfigurationFn != nil {
		return c.PatchMachineConfigurationFn(params)
	}

	return nil, nil
}

func (c *MockClient) PatchMemoryHotplug(params *ops.PatchMemoryHotplugParams, opts ...ops.ClientOption) (*ops.PatchMemoryHotplugNoContent, error) {
	if c.PatchMemoryHotplugFn != nil {
		return c.PatchMemoryHotplugFn(params)
	}

	return nil, nil
}

func (c *MockClient) PatchMemoryHotplugContext(ctx context.Context, params *ops.PatchMemoryHotplugParams, opts ...ops.ClientOption) (*ops.PatchMemoryHotplugNoContent, error) {
	if c.PatchMemoryHotplugFn != nil {
		return c.PatchMemoryHotplugFn(params)
	}

	return nil, nil
}

func (c *MockClient) PatchMmds(params *ops.PatchMmdsParams, opts ...ops.ClientOption) (*ops.PatchMmdsNoContent, error) {
	if c.PatchMmdsFn != nil {
		return c.PatchMmdsFn(params)
	}

	return nil, nil
}

func (c *MockClient) PatchMmdsContext(ctx context.Context, params *ops.PatchMmdsParams, opts ...ops.ClientOption) (*ops.PatchMmdsNoContent, error) {
	if c.PatchMmdsFn != nil {
		return c.PatchMmdsFn(params)
	}

	return nil, nil
}

func (c *MockClient) PatchVM(params *ops.PatchVMParams, opts ...ops.ClientOption) (*ops.PatchVMNoContent, error) {
	if c.PatchVMFn != nil {
		return c.PatchVMFn(params)
	}

	return nil, nil
}

func (c *MockClient) PatchVMContext(ctx context.Context, params *ops.PatchVMParams, opts ...ops.ClientOption) (*ops.PatchVMNoContent, error) {
	if c.PatchVMFn != nil {
		return c.PatchVMFn(params)
	}

	return nil, nil
}

func (c *MockClient) PutBalloon(params *ops.PutBalloonParams, opts ...ops.ClientOption) (*ops.PutBalloonNoContent, error) {
	if c.PutBalloonFn != nil {
		return c.PutBalloonFn(params)
	}

	return nil, nil
}

func (c *MockClient) PutBalloonContext(ctx context.Context, params *ops.PutBalloonParams, opts ...ops.ClientOption) (*ops.PutBalloonNoContent, error) {
	if c.PutBalloonFn != nil {
		return c.PutBalloonFn(params)
	}

	return nil, nil
}

func (c *MockClient) PutCPUConfiguration(params *ops.PutCPUConfigurationParams, opts ...ops.ClientOption) (*ops.PutCPUConfigurationNoContent, error) {
	if c.PutCPUConfigurationFn != nil {
		return c.PutCPUConfigurationFn(params)
	}

	return nil, nil
}

func (c *MockClient) PutCPUConfigurationContext(ctx context.Context, params *ops.PutCPUConfigurationParams, opts ...ops.ClientOption) (*ops.PutCPUConfigurationNoContent, error) {
	if c.PutCPUConfigurationFn != nil {
		return c.PutCPUConfigurationFn(params)
	}

	return nil, nil
}

func (c *MockClient) PutEntropyDevice(params *ops.PutEntropyDeviceParams, opts ...ops.ClientOption) (*ops.PutEntropyDeviceNoContent, error) {
	if c.PutEntropyDeviceFn != nil {
		return c.PutEntropyDeviceFn(params)
	}

	return nil, nil
}

func (c *MockClient) PutEntropyDeviceContext(ctx context.Context, params *ops.PutEntropyDeviceParams, opts ...ops.ClientOption) (*ops.PutEntropyDeviceNoContent, error) {
	if c.PutEntropyDeviceFn != nil {
		return c.PutEntropyDeviceFn(params)
	}

	return nil, nil
}

func (c *MockClient) PutGuestBootSource(params *ops.PutGuestBootSourceParams, opts ...ops.ClientOption) (*ops.PutGuestBootSourceNoContent, error) {
	if c.PutGuestBootSourceFn != nil {
		return c.PutGuestBootSourceFn(params)
	}

	return nil, nil
}

func (c *MockClient) PutGuestBootSourceContext(ctx context.Context, params *ops.PutGuestBootSourceParams, opts ...ops.ClientOption) (*ops.PutGuestBootSourceNoContent, error) {
	if c.PutGuestBootSourceFn != nil {
		return c.PutGuestBootSourceFn(params)
	}

	return nil, nil
}

func (c *MockClient) PutGuestDriveByID(params *ops.PutGuestDriveByIDParams, opts ...ops.ClientOption) (*ops.PutGuestDriveByIDNoContent, error) {
	if c.PutGuestDriveByIDFn != nil {
		return c.PutGuestDriveByIDFn(params)
	}

	return nil, nil
}

func (c *MockClient) PutGuestDriveByIDContext(ctx context.Context, params *ops.PutGuestDriveByIDParams, opts ...ops.ClientOption) (*ops.PutGuestDriveByIDNoContent, error) {
	if c.PutGuestDriveByIDFn != nil {
		return c.PutGuestDriveByIDFn(params)
	}

	return nil, nil
}

func (c *MockClient) PutGuestNetworkInterfaceByID(params *ops.PutGuestNetworkInterfaceByIDParams, opts ...ops.ClientOption) (*ops.PutGuestNetworkInterfaceByIDNoContent, error) {
	if c.PutGuestNetworkInterfaceByIDFn != nil {
		return c.PutGuestNetworkInterfaceByIDFn(params)
	}

	return nil, nil
}

func (c *MockClient) PutGuestNetworkInterfaceByIDContext(ctx context.Context, params *ops.PutGuestNetworkInterfaceByIDParams, opts ...ops.ClientOption) (*ops.PutGuestNetworkInterfaceByIDNoContent, error) {
	if c.PutGuestNetworkInterfaceByIDFn != nil {
		return c.PutGuestNetworkInterfaceByIDFn(params)
	}

	return nil, nil
}

func (c *MockClient) PutGuestPmemByID(params *ops.PutGuestPmemByIDParams, opts ...ops.ClientOption) (*ops.PutGuestPmemByIDNoContent, error) {
	if c.PutGuestPmemByIDFn != nil {
		return c.PutGuestPmemByIDFn(params)
	}

	return nil, nil
}

func (c *MockClient) PutGuestPmemByIDContext(ctx context.Context, params *ops.PutGuestPmemByIDParams, opts ...ops.ClientOption) (*ops.PutGuestPmemByIDNoContent, error) {
	if c.PutGuestPmemByIDFn != nil {
		return c.PutGuestPmemByIDFn(params)
	}

	return nil, nil
}

func (c *MockClient) PutGuestVsock(params *ops.PutGuestVsockParams, opts ...ops.ClientOption) (*ops.PutGuestVsockNoContent, error) {
	if c.PutGuestVsockFn != nil {
		return c.PutGuestVsockFn(params)
	}

	return nil, nil
}

func (c *MockClient) PutGuestVsockContext(ctx context.Context, params *ops.PutGuestVsockParams, opts ...ops.ClientOption) (*ops.PutGuestVsockNoContent, error) {
	if c.PutGuestVsockFn != nil {
		return c.PutGuestVsockFn(params)
	}

	return nil, nil
}

func (c *MockClient) PutLogger(params *ops.PutLoggerParams, opts ...ops.ClientOption) (*ops.PutLoggerNoContent, error) {
	if c.PutLoggerFn != nil {
		return c.PutLoggerFn(params)
	}

	return nil, nil
}

func (c *MockClient) PutLoggerContext(ctx context.Context, params *ops.PutLoggerParams, opts ...ops.ClientOption) (*ops.PutLoggerNoContent, error) {
	if c.PutLoggerFn != nil {
		return c.PutLoggerFn(params)
	}

	return nil, nil
}

func (c *MockClient) PutMachineConfiguration(params *ops.PutMachineConfigurationParams, opts ...ops.ClientOption) (*ops.PutMachineConfigurationNoContent, error) {
	if c.PutMachineConfigurationFn != nil {
		return c.PutMachineConfigurationFn(params)
	}

	return nil, nil
}

func (c *MockClient) PutMachineConfigurationContext(ctx context.Context, params *ops.PutMachineConfigurationParams, opts ...ops.ClientOption) (*ops.PutMachineConfigurationNoContent, error) {
	if c.PutMachineConfigurationFn != nil {
		return c.PutMachineConfigurationFn(params)
	}

	return nil, nil
}

func (c *MockClient) PutMemoryHotplug(params *ops.PutMemoryHotplugParams, opts ...ops.ClientOption) (*ops.PutMemoryHotplugNoContent, error) {
	if c.PutMemoryHotplugFn != nil {
		return c.PutMemoryHotplugFn(params)
	}

	return nil, nil
}

func (c *MockClient) PutMemoryHotplugContext(ctx context.Context, params *ops.PutMemoryHotplugParams, opts ...ops.ClientOption) (*ops.PutMemoryHotplugNoContent, error) {
	if c.PutMemoryHotplugFn != nil {
		return c.PutMemoryHotplugFn(params)
	}

	return nil, nil
}

func (c *MockClient) PutMetrics(params *ops.PutMetricsParams, opts ...ops.ClientOption) (*ops.PutMetricsNoContent, error) {
	if c.PutMetricsFn != nil {
		return c.PutMetricsFn(params)
	}

	return nil, nil
}

func (c *MockClient) PutMetricsContext(ctx context.Context, params *ops.PutMetricsParams, opts ...ops.ClientOption) (*ops.PutMetricsNoContent, error) {
	if c.PutMetricsFn != nil {
		return c.PutMetricsFn(params)
	}

	return nil, nil
}

func (c *MockClient) PutMmds(params *ops.PutMmdsParams, opts ...ops.ClientOption) (*ops.PutMmdsNoContent, error) {
	if c.PutMmdsFn != nil {
		return c.PutMmdsFn(params)
	}

	return nil, nil
}

func (c *MockClient) PutMmdsContext(ctx context.Context, params *ops.PutMmdsParams, opts ...ops.ClientOption) (*ops.PutMmdsNoContent, error) {
	if c.PutMmdsFn != nil {
		return c.PutMmdsFn(params)
	}

	return nil, nil
}

func (c *MockClient) PutMmdsConfig(params *ops.PutMmdsConfigParams, opts ...ops.ClientOption) (*ops.PutMmdsConfigNoContent, error) {
	if c.PutMmdsConfigFn != nil {
		return c.PutMmdsConfigFn(params)
	}

	return nil, nil
}

func (c *MockClient) PutMmdsConfigContext(ctx context.Context, params *ops.PutMmdsConfigParams, opts ...ops.ClientOption) (*ops.PutMmdsConfigNoContent, error) {
	if c.PutMmdsConfigFn != nil {
		return c.PutMmdsConfigFn(params)
	}

	return nil, nil
}

func (c *MockClient) PutSerialDevice(params *ops.PutSerialDeviceParams, opts ...ops.ClientOption) (*ops.PutSerialDeviceNoContent, error) {
	if c.PutSerialDeviceFn != nil {
		return c.PutSerialDeviceFn(params)
	}

	return nil, nil
}

func (c *MockClient) PutSerialDeviceContext(ctx context.Context, params *ops.PutSerialDeviceParams, opts ...ops.ClientOption) (*ops.PutSerialDeviceNoContent, error) {
	if c.PutSerialDeviceFn != nil {
		return c.PutSerialDeviceFn(params)
	}

	return nil, nil
}

func (c *MockClient) StartBalloonHinting(params *ops.StartBalloonHintingParams, opts ...ops.ClientOption) (*ops.StartBalloonHintingNoContent, error) {
	if c.StartBalloonHintingFn != nil {
		return c.StartBalloonHintingFn(params)
	}

	return nil, nil
}

func (c *MockClient) StartBalloonHintingContext(ctx context.Context, params *ops.StartBalloonHintingParams, opts ...ops.ClientOption) (*ops.StartBalloonHintingNoContent, error) {
	if c.StartBalloonHintingFn != nil {
		return c.StartBalloonHintingFn(params)
	}

	return nil, nil
}

func (c *MockClient) StopBalloonHinting(params *ops.StopBalloonHintingParams, opts ...ops.ClientOption) (*ops.StopBalloonHintingNoContent, error) {
	if c.StopBalloonHintingFn != nil {
		return c.StopBalloonHintingFn(params)
	}

	return nil, nil
}

func (c *MockClient) StopBalloonHintingContext(ctx context.Context, params *ops.StopBalloonHintingParams, opts ...ops.ClientOption) (*ops.StopBalloonHintingNoContent, error) {
	if c.StopBalloonHintingFn != nil {
		return c.StopBalloonHintingFn(params)
	}

	return nil, nil
}

func (c *MockClient) SetTransport(transport runtime.ContextualTransport) {
	c.SetTransport(transport)
}
